# Generated by Django 5.1 on 2024-08-25 06:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('e2d23a1a-2e44-4a65-8f57-f805eeec143a'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('98fdfa05-8d17-4b73-b285-66600f91dc63'), max_length=255, null=True, unique=True),
        ),
    ]
