# Generated by Django 5.1.2 on 2024-10-22 16:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('87f34265-3589-4a3a-ab8d-8fb63abbc5a5'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('bea915d8-bad8-4a98-91df-e1555a540757'), max_length=255, null=True, unique=True),
        ),
    ]
