# Generated by Django 5.1.2 on 2024-10-22 17:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('81cb0e1c-6307-43c6-9e33-585d9b3c8572'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('3d0d5785-8474-4508-b188-c9a3f1328b4f'), max_length=255, null=True, unique=True),
        ),
    ]
