# Generated by Django 5.1.2 on 2024-10-22 17:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('605984ba-ded4-4ad8-b5c2-0c32259d8c45'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('29342b4e-bd82-4156-8bb2-026869951244'), max_length=255, null=True, unique=True),
        ),
    ]
