# Generated by Django 5.1.2 on 2024-10-25 05:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('818eb004-83a4-4d15-96d4-2544f1d4901e'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('69cb3b51-9be9-4fe1-a674-05dc40ae293a'), max_length=255, null=True, unique=True),
        ),
    ]
