# Generated by Django 5.1.2 on 2024-10-25 05:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('4a62f296-fcc9-448f-9a54-0c24bb79e84d'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('491f0aad-008c-498e-ac85-0416c829c6e7'), max_length=255, null=True, unique=True),
        ),
    ]
