# Generated by Django 5.1.2 on 2024-10-26 04:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('86fec8c8-ac16-400c-93ce-6328344659b9'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('4f6bd37a-7996-46d0-9af9-2880a74546f0'), max_length=255, null=True, unique=True),
        ),
    ]
