# Generated by Django 5.1.2 on 2024-10-26 05:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonUtils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='#Buge')),
                ('version', models.DecimalField(decimal_places=1, default=0.1, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('47d5f6b2-8a6e-43c4-8441-2c2372d4e421'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('1703d110-0e08-4239-9797-f0e5956b5369'), max_length=255, null=True, unique=True),
        ),
    ]
