# Generated by Django 5.1.2 on 2024-10-26 05:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_commonutils_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('7f5699af-ef25-4792-8f53-56b5dcbadb8c'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('23a9c578-10b1-46a5-8f2e-8fa1719a9cef'), max_length=255, null=True, unique=True),
        ),
    ]
