# Generated by Django 5.1.2 on 2024-10-26 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('5085d18f-86c3-4677-9a9b-751d2cc14bcf'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('dbaf8e50-90ee-48f7-b05b-594684f28f4e'), max_length=255, null=True, unique=True),
        ),
    ]
