# Generated by Django 5.1.2 on 2024-10-26 15:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('352c98f3-06ce-4f45-a525-580cb6a6e986'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('e54b0dff-01df-473d-ae82-13d909b61318'), max_length=255, null=True, unique=True),
        ),
    ]
