# Generated by Django 5.1.2 on 2024-10-28 05:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('8f251024-2a7b-4631-affa-7d0cf774700b'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('a7a00cca-4120-44b4-9bea-49168de5de97'), max_length=255, null=True, unique=True),
        ),
    ]
