# Generated by Django 5.1.2 on 2024-10-31 14:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('1ef751ef-4ca9-46e1-8c79-e2a3fd69d758'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('030f812e-2e65-4a52-9cd7-d3eb498d229a'), max_length=255, null=True, unique=True),
        ),
    ]
