# Generated by Django 5.1.2 on 2024-10-31 14:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('baa94b30-6cc4-4b16-9e5c-69213310de25'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('644d00dd-6b82-44eb-bce2-598ab3bf37f4'), max_length=255, null=True, unique=True),
        ),
    ]
