# Generated by Django 5.1.2 on 2024-11-15 14:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('26fabae3-2302-48ff-9586-2203a4322fdc'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('28c40efd-12d1-477a-8699-8f4b1baf79ee'), max_length=255, null=True, unique=True),
        ),
    ]
