# Generated by Django 5.1.2 on 2024-11-15 14:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_api_key_alter_jsonserializer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('27f8e323-835b-49f5-86cf-e888bb47d4e7'), max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='key',
            field=models.CharField(blank=True, default=uuid.UUID('544586b5-769a-48b2-943b-9e5aea8e0491'), max_length=255, null=True, unique=True),
        ),
    ]
