# Generated by Django 5.1.2 on 2024-10-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('english_keywords', models.JSONField(blank=True, default=list, null=True)),
                ('spanish_keywords', models.JSONField(blank=True, default=list, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='product_thumbnails/')),
            ],
        ),
    ]
