# Generated by Django 5.1.2 on 2024-10-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_otherinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfigurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('system_instruction', models.TextField(blank=True, null=True)),
                ('temperature', models.CharField(blank=True, max_length=255, null=True)),
                ('top_p', models.CharField(blank=True, max_length=255, null=True)),
                ('top_k', models.CharField(blank=True, max_length=255, null=True)),
                ('max_output_tokens', models.CharField(blank=True, max_length=255, null=True)),
                ('response_mime_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
