# Generated by Django 5.1.2 on 2024-10-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_product_audio_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfigurations',
            name='post_welcome_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelconfigurations',
            name='welcome_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
