# Generated by Django 5.1.2 on 2024-10-26 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_model_modelconfiguration_delete_modelconfigurations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('other_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelConfigurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('system_instruction', models.TextField(blank=True, null=True)),
                ('temperature', models.CharField(blank=True, max_length=255, null=True)),
                ('top_p', models.CharField(blank=True, max_length=255, null=True)),
                ('top_k', models.CharField(blank=True, max_length=255, null=True)),
                ('max_output_tokens', models.CharField(blank=True, max_length=255, null=True)),
                ('response_mime_type', models.CharField(blank=True, max_length=255, null=True)),
                ('welcome_text', models.TextField(blank=True, null=True)),
                ('post_welcome_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='modelconfiguration',
            name='model',
        ),
        migrations.CreateModel(
            name='LLMModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.llmmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.DeleteModel(
            name='ModelConfiguration',
        ),
    ]
