# Generated by Django 5.1.2 on 2024-10-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='cart_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
