# Generated by Django 5.1.2 on 2024-11-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_setting_cart_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='ModelSetting',
        ),
    ]
